ckpt: last
resume_dir: null

run_dir: outputs/${hydra:runtime.choices.model}_${hydra:runtime.choices.data}_${hydra:runtime.choices.data/motion_loader}

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 32
  num_workers: 8

defaults:
  - data: kitml  #kitml
  - model: tmr
  - trainer
  - defaults
  - _self_
